apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: activemq
  namespace: djin-shared
spec:
  replicas: 3
  selector:
    matchLabels:
      app: activemq
  serviceName: activemq
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: activemq
    spec:
      containers:
        - env:
            - name: NAMESPACE
              value: djin-shared
            - name: ACTIVEMQ_DB_HOSTNAME
              value: ep-utils-db.cp4u2wlfefuk.us-east-1.rds.amazonaws.com
            - name: ACTIVEMQ_DB_USER
              value: epadmin
            - name: ACTIVEMQ_DB_PASSWORD
              value: EPadm\!n0
            - name: ACTIVEMQ_CONNECTOR_URI
              value: >-
                static:(tcp://activemq-0:61616,tcp://activemq-1:61616,tcp://activemq-2:61616)?maxReconnectDelay=5000&amp;useExponentialBackOff=false
          image: 'artifactory.dowjones.io:5000/djin/productivity/activemq:latest'
          name: activemq
          ports:
            - containerPort: 8161
              name: http
              protocol: TCP
            - containerPort: 61616
              name: tcp
              protocol: TCP
            - containerPort: 5672
            - containerPort: 61613
            - containerPort: 1883
            - containerPort: 61614
      imagePullSecrets:
        - name: artifactorycred
      terminationGracePeriodSeconds: 10
